ptest :-
   new(W, auto_sized_picture(sodt)),
   send(W, max_size, size(2000, 600)),
   send(W, display, new(Plotter, plotter)),
   send(Plotter, axis, plot_axis(x, 0.0, 1000, @(default), 1000)),
   send(Plotter, axis, plot_axis(y, 0.0, 500, @(default), 500)),
   send(Plotter, graph, new(Green_Plot, plot_graph)),
   send(Green_Plot, colour, green),
   send(Plotter, graph, new(Blue_Plot, plot_graph)),
   send(Blue_Plot, colour, blue),
   send(Plotter, graph, new(Orange_Plot, plot_graph)),
   send(Orange_Plot, colour, orange),
   send(W, open),
   between(1, 500, I),
   send(Green_Plot, append, I, I),
   I1 is I + 100,
   send(Blue_Plot, append, I1, I),
   I2 is I + 200,
   send(Orange_Plot, append, I2, I),
%   sleep(0.01),
   fail.
